"""empty message

Revision ID: 6dfb377a8a04
Revises: 879054951b2c
Create Date: 2022-06-22 11:41:45.203042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfb377a8a04'
down_revision = '879054951b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('saying', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cat', 'saying')
    # ### end Alembic commands ###
