"""empty message

Revision ID: 879054951b2c
Revises: f99301e367bc
Create Date: 2022-05-10 10:15:51.255540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879054951b2c'
down_revision = 'f99301e367bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('human_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cat', 'human', ['human_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cat', type_='foreignkey')
    op.drop_column('cat', 'human_id')
    # ### end Alembic commands ###
